### PR TITLE
Add nano

### PR DESCRIPTION
**Pull request by benyanke**
I use nano daily - would see value in having it there.

### CODE REVIEW

**Comment by rylandg** [comment]
Do you happen to know what the current size of nano is? I assume it's incredibly small, and if so will 100% merge. Thanks so much for the PR.

**Comment by benyanke** [comment]
It's about 250k so I think we're good:

```
└──╼ ll `which nano`
-rwxr-xr-x 1 root root 241K Mar  6  2018 /bin/nano

```

**Comment by rylandg** [comment]
@all-contributors please add @benyanke for adding basic nano support
@all-contributors please add @rylandg for creating the project
@all-contributors please add @marcopiraccini for bug hunting
@all-contributors please add @tokelove for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @benyanke for adding basic nano support

**Comment by rylandg** [comment]
@all-contributors please add @benyanke for adding the code allowing basic nano support

**Comment by rylandg** [comment]
@all-contributors please add @marcopiraccini for bug hunting
@all-contributors please add @tokelove for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @marcopiraccini for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @tokelove for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @rylandg for creating the project and blog

**Comment by rylandg** [comment]
@all-contributors please add @marcopiraccini for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @tokelove for bug hunting

**Comment by rylandg** [comment]
@all-contributors please add @rylandg for creating the project and blog

**Pull request merged**
